image: node:10

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm --version
          - node --version
          - npm install -g lerna
          - lerna bootstrap
          - npm test
