image: node:16

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm --version
          - node --version
          - npm install -g lerna
          - lerna bootstrap
          - npm test
  custom:
    ci-scan-repo:
      - step:
          name: CI scanner
          image:
            name: forlagshuset.azurecr.io/ci-scanner:prod
            username: $CI_REGISTRY_USER
            password: $CI_REGISTRY_SECRET
          services:
            - docker
          script:
            - /scanner/run
